<% @TinyPG Namespace="Mocca" %>

// Terminals:
BRACKETOPEN      	-> @"\(";
BRACKETCLOSE     	-> @"\)";
MIDDLEOPEN     		-> @"\{";
MIDDLECLOSE			-> @"\}";
COMMA				-> @"\,";
SQUAREOPEN			-> @"\[";
SQUARECLOSE			-> @"\]";
SEMICOLON        	-> @";";
IDENTIFIER        	-> @"[a-zA-Z_][a-zA-Z0-9_]*";
NUMBER	      	    -> @"[0-9]+";
EOF               	-> @"^$";
STRING             	-> @"@?\""(\""\""|[^\""])*\""";
BLOCKGROUP			-> @"blockgroup";

[Skip]
WHITESPACE        	-> @"\s+";

[Skip]
COMMENTLINE       	-> @"//[^\n]*\n?";

[Skip]
COMMENTBLOCK      	-> @"/\*[^*]*\*+(?:[^/*][^*]*\*+)*/";

// Production lines LL(1):
Start			-> Blockgroup* EOF;
Blockgroup		-> BLOCKGROUP Params Block;
Params			-> BRACKETOPEN Param BRACKETCLOSE;
Param			-> Expression (COMMA Expression)*;
Expression		-> Symbol | Atom;
Symbol			-> IDENTIFIER (Params)*;
Atom			-> NUMBER | STRING | Array | Dictionary;
Array			-> SQUAREOPEN Param SQUARECLOSE;
Dictionary		-> MIDDLEOPEN Params (COMMA Params)* MIDDLECLOSE;
Block			-> MIDDLEOPEN StatementList* MIDDLECLOSE;
StatementList	-> Statement*;
Statement		-> IDENTIFIER Params (Block)* (SEMICOLON)*;
